export const inventoryDecisionContent = {
  title: 'Inventory decision history',
  detail: 'Compare confirmed selections with the preceding confirmed shortlist for the same media mix. Independent campaign options are not replacements. A removal and an addition are not proof of a one-to-one replacement.',
  supplierDetail: 'Your inventory only. Client, campaign, planner identity and private decision notes are withheld. Report references support an authorised follow-up.',
  empty: 'No confirmed selection decisions have been recorded yet.',
  unavailable: 'Decision history could not be loaded.',
  load: 'Open decision history',
  loading: 'Loading decision history…',
  source: 'Eligibility and ranking are deterministic planning calculations. Final selections are separately recorded with their decision history.',
  omitted: 'No longer present in the current shortlist',
  selected: 'Selected',
  retained: 'Kept in this selection',
  added: 'Added to this selection',
  removed: 'Removed from this selection',
  declined: 'Shortlisted, not carried forward',
  privateReason: 'Private planner notes withheld',
  missingReason: 'No decision reason was supplied',
  loadOlder: 'Load older decisions',
  loadingOlder: 'Loading older decisions…',
  reasonLabel: 'Why are you carrying these placements forward?',
  reasonHelp: 'Record the buying trade-off and why alternatives were excluded. This note is retained privately with the confirmed selection, not shared automatically with suppliers.',
} as const
