export const placeCopy = {
  title: 'Find placements near a place',
  introduction: 'Add a specific shop, branch or landmark and the distance around it. Planning checks inventory against this area.',
  limitation: 'Find a mapped branch when the location service is connected, search supplied inventory evidence, or enter an evidenced location. Always confirm the exact branch and distance before planning.',
  mappedSearch: 'Branch or landmark and area',
  mappedHint: 'For example: Clicks, Sandton, South Africa',
  searchMapped: 'Find mapped branches',
  mappedPrivacy: 'Only the place and area you enter are sent to the location service. Do not include client, audience or confidential campaign details. Search runs when you click, not while typing.',
  chooseMapped: 'These mapped places are candidates, not verified retailer records. Choose the exact branch; do not use a similarly named location.',
  noMappedResults: 'No mapped branch matched. Refine the branch and area or supply an evidenced location. This does not establish that no branch exists.',
  viewSource: 'Review mapped location',
  attribution: '© OpenStreetMap contributors · ODbL',
  servicePolicy: 'Location service usage policy',
  searchTitle: 'Search supplied place evidence',
  search: 'Search places',
  searching: 'Searching…',
  noResults: 'No matching place with its own coordinates was found in supplied inventory. Enter a location from a source you can verify below; a nearby screen’s coordinates are not the shop’s location.',
  choose: 'Choose the exact location and check its source. Results are limited to 20; refine the branch name if needed.',
  searchError: 'Place search is unavailable. Try again or supply a verifiable location below.',
  importedContext: 'Inventory source context, not a verified branch address:',
  usePlace: 'Use location:',
  selected: 'Location copied below. Set a distance, add it for review, then verify the exact branch and source.',
  name: 'Place or branch name',
  nameHint: 'For example, the exact Clicks or Dis-Chem branch',
  latitude: 'Latitude',
  longitude: 'Longitude',
  radius: 'Distance around this place (metres)',
  source: 'Location source or reference',
  sourceHint: 'Source link or reference identifying this exact branch',
  add: 'Add place for review',
  added: 'Place added. Verify its position and source in the geography requirements below.',
  invalid: 'Supply a place name, source reference, valid latitude and longitude, and a distance greater than zero.',
}
