export const buyAssessmentContent = {
  title: 'What does this buy deliver?',
  supplierCost: 'Supplier cost for the planned dates and purchase quantity',
  costCaveat: 'Supplier cost is not the client quote: fees, tax and final commercial terms still apply.',
  baseline: 'Supplied audience measurement — not a campaign forecast',
  target: 'Measurement universe matches the approved target name; review the source definition.',
  nonTarget: 'This measurement is not established as reach of your approved target audience.',
  unknown: 'Not supplied or not comparable',
  reach: 'People reached in supplied measurement',
  impressions: 'Supplied impressions',
  frequency: 'Impressions per person in supplied measurement',
  cpm: 'Supplier cost per 1,000 supplied impressions',
  cpp: 'Supplier cost per supplied person reached',
  ratioCaveat: 'These are baseline comparisons, not promised delivery or achieved campaign performance.',
  digital: 'Digital screen exposure',
  creative: 'Creative duration (seconds)',
  slot: 'Booked slot duration (seconds)',
  loop: 'Loop duration (seconds)',
  plays: 'Plays per loop',
  share: 'Time share of the loop (%)',
  loopCaveat: 'Time share is not audience share. Operating hours, contracted plays, viewing conditions and campaign delivery still need evidence.',
  source: 'Source', period: 'Measurement period', universe: 'Measured audience', methodology: 'Method',
} as const
