export const combinationContent = {
  title: 'Compare coverage combinations',
  explanation: 'These alternatives cover the required areas and media channels within supplier-cost ceilings. They are starting points for a planner, not optimised audience plans.',
  caveat: 'Client pricing, fees and tax still need assessment. Audience rollups appear only when compatible measured evidence exists; Advertified never treats summed placement reach as unique campaign reach.',
  truncated: 'The search was bounded for responsiveness. Other combinations may exist.',
  none: 'No combination was found in the evaluated candidates. This does not establish that no suitable campaign can be built.',
  missing: 'Eligible placements lack a comparable campaign supplier cost and could not enter this comparison:',
  use: 'Review this combination', supplier: 'Combined supplier cost',
  selection: 'This replaces your current selection for review. Confirming inventory remains a separate action.',
  option: 'Combination', comparison: 'Difference from recommended plan', sameCost: 'Same supplier cost',
  recommended: 'Recommended plan', maximumReach: 'Maximum measured reach', higherFrequency: 'Higher measured frequency',
  lowerCost: 'Lower supplier cost', alternative: 'Alternative supply mix',
  added: 'Adds', removed: 'Removes', unchanged: 'No placement changes',
  targetCount: 'Placements with measured target baselines', missingDelivery: 'Placements without compatible reach or impressions',
  supplierCount: 'Distinct inventory tenant sources', roles: 'Planned channel roles',
  audienceForecast: 'Measured campaign audience evidence', grossReach: 'Gross placement reach',
  deduplicatedReach: 'Deduplicated campaign reach', duplicatedReach: 'Duplicated audience',
  impressions: 'Total impressions', frequency: 'Average frequency', incremental: 'Incremental reach',
  audienceBasis: 'Measurement basis', audienceGaps: 'Audience evidence still needed',
  unknownCandidate: 'Placement no longer available in this shortlist',
} as const
