// <auto-generated />
using Advertified.Commercial.Infrastructure.MasterData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Advertified.Commercial.Infrastructure.Migrations;

[DbContext(typeof(GovernanceDbContext))]
public sealed partial class GovernanceDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.23")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "Advertified.Commercial.Infrastructure.MasterData.MasterDataItem",
            entity =>
            {
                entity.Property<string>("CollectionCode")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("collection_code");
                entity.Property<string>("Code")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("code");
                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");
                entity.Property<string>("DisplayLabel")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("display_label");
                entity.Property<DateOnly>("EffectiveFrom")
                    .HasColumnType("date")
                    .HasColumnName("effective_from");
                entity.Property<DateOnly?>("EffectiveTo")
                    .HasColumnType("date")
                    .HasColumnName("effective_to");
                entity.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");
                entity.Property<string>("MetadataJson")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("metadata_json");
                entity.Property<int>("SortOrder")
                    .HasColumnType("integer")
                    .HasColumnName("sort_order");
                entity.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                entity.HasKey("CollectionCode", "Code")
                    .HasName("pk_master_data_items");
                entity.HasIndex("CollectionCode", "SortOrder")
                    .IsUnique()
                    .HasDatabaseName("ux_master_data_items_collection_sort");
                entity.ToTable(
                    "master_data_items",
                    "governance",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_master_data_items_effective_dates",
                            "effective_to IS NULL OR effective_to > effective_from");
                        table.HasCheckConstraint(
                            "ck_master_data_items_sort_order",
                            "sort_order > 0");
                    });
            });

        modelBuilder.Entity(
            "Advertified.Commercial.Infrastructure.MasterData.MasterDataItemHistory",
            entity =>
            {
                entity.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(
                    entity.Property<long>("Id"));
                entity.Property<DateTimeOffset>("ChangedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("changed_at_utc");
                entity.Property<string>("CollectionCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("collection_code");
                entity.Property<string>("ItemCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("item_code");
                entity.Property<string>("Operation")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)")
                    .HasColumnName("operation");
                entity.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("snapshot_json");

                entity.HasKey("Id").HasName("pk_master_data_item_history");
                entity.HasIndex("CollectionCode", "ItemCode", "ChangedAtUtc")
                    .HasDatabaseName("ix_master_data_history_item_time");
                entity.ToTable("master_data_item_history", "governance");
            });

        modelBuilder.Entity(
            "Advertified.Commercial.Infrastructure.MasterData.MasterDataSet",
            entity =>
            {
                entity.Property<string>("Code")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("code");
                entity.Property<DateOnly>("EffectiveFrom")
                    .HasColumnType("date")
                    .HasColumnName("effective_from");
                entity.Property<string>("RegistryVersion")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("registry_version");
                entity.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                entity.HasKey("Code").HasName("pk_master_data_collections");
                entity.ToTable("master_data_collections", "governance");
            });

        modelBuilder.Entity(
            "Advertified.Commercial.Infrastructure.MasterData.MasterDataItem",
            entity =>
            {
                entity.HasOne(
                        "Advertified.Commercial.Infrastructure.MasterData.MasterDataSet",
                        null)
                    .WithMany()
                    .HasForeignKey("CollectionCode")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_master_data_items_collections");
            });

        BuildCommercialIdentityModel(modelBuilder);
        BuildCommercialBusinessModel(modelBuilder);
        BuildCommercialPlatformModel(modelBuilder);
    }
}
