param(
    [Parameter(Mandatory = $true)][string]$Container,
    [Parameter(Mandatory = $true)][string]$Database,
    [Parameter(Mandatory = $true)][string]$Username,
    [Parameter(Mandatory = $true)][string]$OutputPath
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# This generator reads schema only from an explicitly named disposable verification
# container. It never captures table data, migration history, credentials or roles.
if (-not $Container.StartsWith('advertified-baseline-', [StringComparison]::Ordinal)) {
    throw 'Only an explicitly named advertified-baseline- verification container is allowed.'
}
$dump = & docker exec $Container pg_dump -U $Username -d $Database `
    --schema-only --no-owner --no-comments --schema=governance --schema=commercial
if ($LASTEXITCODE -ne 0) { throw 'Disposable schema export failed.' }
$lines = @('-- <auto-generated /> Schema-only PostgreSQL baseline; do not hand-edit.')
$lines += @('-- Regenerate with tools/export-database-baseline.ps1 from a disposable verified database.')
$lines += $dump | Where-Object {
    $_ -notmatch '^--' -and $_ -notmatch '^\\(un)?restrict ' -and $_.Trim().Length -gt 0 -and
    $_ -notmatch "^SELECT pg_catalog.set_config\('search_path'"
} | ForEach-Object {
    # pg_dump settings must not leak outside EF's migration transaction.
    if ($_ -match '^SET ') { $_ -replace '^SET ', 'SET LOCAL ' }
    else { $_ }
}
$resolvedOutput = [IO.Path]::GetFullPath($OutputPath)
[IO.File]::WriteAllText($resolvedOutput, ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Get-FileHash -LiteralPath $resolvedOutput -Algorithm SHA256
