<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src/**/*.cs" />
    <Compile Remove="tests/**/*.cs" />
    <Content Remove="src/**/*" />
    <Content Remove="tests/**/*" />
    <EmbeddedResource Remove="src/**/*" />
    <EmbeddedResource Remove="tests/**/*" />
    <None Remove="src/**/*" />
    <None Remove="tests/**/*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src/Advertified.Commercial.Application/Advertified.Commercial.Application.csproj" />
    <ProjectReference Include="src/Advertified.Commercial.Infrastructure/Advertified.Commercial.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
</Project>
